version: '2.1'
orbs:
  azure-cli: circleci/azure-cli@1.0.0
jobs:
  login-to-azure:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - azure-cli/login-with-user:
          alternate-tenant: true
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_TENANT` env var
workflows:
  example-workflow:
    jobs:
      - login-to-azure


checkout:
  terraform: circleci/terraform@3.1
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - terraform/plan

  
